server:
  port: 8080

  tomcat:
    basedir: ./
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    session:
      timeout: 60m

spring:
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true
  application:
    name: maru2
  freemarker:
    suffix: .ftl
    cache: false